#!/bin/bash

echo "~> git fetch --all --tags"
git fetch --all --tags

TAG=${1}
if [[ "${TAG}" == "" || "${TAG}" == "latest" ]]; then    
    TAG=$( git latest-version )
elif [[ "${TAG}" == "rollback" || "${TAG}" == "previous" ]]; then
    TAG=$( git previous-version )
fi

echo "~> git what \"${TAG}\""
git what "${TAG}" > /dev/null 2> /dev/null  || exit 1

echo "~> git checkout \"${TAG}\""
git checkout "${TAG}"
